# Generated by Django 5.0.6 on 2024-09-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards_db',
            name='hp',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cards_db',
            name='power',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
