# Generated by Django 5.0.6 on 2024-09-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_0', '0002_cards_db_hp_cards_db_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards_db',
            old_name='hp',
            new_name='overhead',
        ),
        migrations.RemoveField(
            model_name='cards_db',
            name='power',
        ),
    ]
