# Generated by Django 5.0.6 on 2024-09-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_0', '0003_rename_hp_cards_db_overhead_remove_cards_db_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards_db',
            name='verso_card_img',
            field=models.ImageField(default=0, upload_to='image_cards'),
            preserve_default=False,
        ),
    ]
